#
# Makefile
#
# makefile: exit
#
# Copyright (C) 2017-2025 Tactical Computing Laboratories, LLC
# All Rights Reserved
# contact@tactcomplabs.com
#
# See LICENSE in the top level directory for licensing details
#

TESTNAME=exit
CCOPTS = -O0 -g3
TARG ?= rev
REV_MACHINE = "CORES:RV64IMAFDC"

include ../mkinc/common.mk

.PHONY: clean
clean:
	rm -f $(TESTNAME).exe $(TESTNAME).d StatisticOutput.csv

#-- EOF
